### ISSUE TITLE
naming :)

### ISSUE THREAD

**Issue by quartzjer** [telehash/interoper#4]
Is there a different name or acronym that would work instead of SUT (system-under-test)? It can just be easily mis-interpreted when spoken.

@fd you also mentioned dev-mode and tournament-mode, I'm not sure what the distinction is yet? For myself I think I'd like to run "everything" frequently in dev mode, just probably in parts for faster iterations?

**Comment by fd** [comment]
> Is there a different name or acronym that would work instead of SUT (system-under-test)? It can just be easily mis-interpreted when spoken.

@quartzjer master/slave instead of driver/sut?

> @fd you also mentioned dev-mode and tournament-mode, I'm not sure what the distinction is yet? For myself I think I'd like to run "everything" frequently in dev mode, just probably in parts for faster iterations?

Say you're working on the C code. In dev mode interoper would build your docker image (locally) and test it against all other implementations. So interoper will not run Js against Go in dev mode (when working on the C code). In tournament mode there is no _local_ image. instead all _official_ implementations will be tested against each other. (Js -> Go, Go -> Js, Js -> C, C -> Js, Go -> C, C -> Go, etc...)

**Comment by quartzjer** [comment]
How about teacher/student, or driver/worker?

I follow now on the modes, tournament is basically just running all of the dev modes automatically, it's not something anyone really needs to do locally for dev, cool!

**Comment by fd** [comment]
@quartzjer I went with driver/worker.

> I follow now on the modes, tournament is basically just running all of the dev modes automatically, it's not something anyone really needs to do locally for dev, cool!

That's correct.
